# ---- mandatory PEP 518 section ----
[build-system]
requires      = ["briefcase>=0.3.22"]
build-backend = "briefcase.build_system"

# ---- PEP 621 project metadata ----
[project]
name = "Transcribrr"
version = "1.0.0"
description = "Speech-to-text transcription tool"
authors = [
    {name = "John Miller", email = "john@johnbmiller.com"}
]
license = {file = "LICENSE"}

[tool.briefcase]
project_name   = "Transcribrr"
bundle         = "com.transcribrr"
version        = "1.0.0"
author         = "John Miller"
author_email   = "john@johnbmiller.com"

# Briefcase already inherits the license declared under [project].
# Having a second declaration here violates the Briefcase configuration
# schema and causes an `AttributeError: can't set attribute` during
# parsing. The `license` key is therefore removed.

# Runtime requirements for the packaging target. These must be provided
# as individual CLI‑tokens so that Briefcase passes them verbatim to
# `pip install`. Using a single string that combines the flag and the
# file path would be interpreted as the value for the `-r` option
# instead of two separate arguments and triggers the same AttributeError
# inside Briefcase's dataclass validation.
requires = [
    "-r",
    "requirements.txt",
]


[tool.briefcase.app.transcribrr]
formal_name  = "Transcribrr"
module_name  = "app"
description  = "Speech‑to‑text transcription tool"
sources      = ["app", "main.py"]   # paths that contain your code
icon         = "icons/app/app_icon.icns"

# ---- macOS‑specific options ----
[tool.briefcase.app.transcribrr.macOS]
# Inherit the same tokenised requirements list so that macOS builds
# receive identical runtime dependencies.
requires = [
    "-r",
    "requirements.txt",
]
resources  = [
    "icons",                       # complete icon tree
    "config.json",
    "preset_prompts.json",
]