# ---- mandatory PEP 518 section ----
[build-system]
requires      = ["briefcase>=0.3.22"]
build-backend = "briefcase.build_system"

[tool.briefcase]
project_name   = "Transcribrr"
bundle         = "com.transcribrr"
version        = "1.0.0"
author         = "John Miller"
author_email   = "john@johnbmiller.com"
license = "GPL-3.0-or-later"                

requires      = [
    "PyQt6",
    "PyQt6-Qt6",
    "appdirs",
    "colorlog",
    "certifi",
]


[tool.briefcase.app.transcribrr]
formal_name  = "Transcribrr"
module_name  = "app"
description  = "Speech‑to‑text transcription tool"
sources      = ["app", "main.py"]   # paths that contain your code
icon         = "icons/app/app_icon.icns"

# ---- macOS‑specific options ----
[tool.briefcase.app.transcribrr.macOS]
requires   = [
    "PyQt6>=6.6.1",
    "transformers>=4.30.0",
    "openai>=1.0.0",
    "keyring>=25.0.0",
    "numpy>=1.20.0",
    "requests>=2.25.0",
    "PyAudio>=0.2.14",
    "pydub>=0.25.1",
    "moviepy==1.0.3",
    "yt-dlp==2025.3.27",
    "soundfile>=0.12.1",
    "ffmpeg-python>=0.2.0",
    "PyPDF2>=3.0.0",
    "python-docx>=0.8.11",
    "htmldocx>=0.0.5",
    "pyannote.audio>=3.0.0",
    "whisperx>=3.3.1",
    "sentencepiece>=0.1.97",
    "ctranslate2>=3.0.0",
    "safetensors>=0.3.1",
    "accelerate>=1.0.0",
    "onnxruntime>=1.10.0",
    "huggingface-hub>=0.16.0",
    "scipy>=1.8.0",
    "decorator==4.4.2",
    "tqdm>=4.60.0",
    "colorlog>=6.0.0",
    "appdirs>=1.4.4"
]                    # Dependencies from requirements.txt
resources  = [
    "icons",                       # complete icon tree
    "config.json",
    "preset_prompts.json",
]
