# ---- mandatory PEP 518 section ----
[build-system]
requires      = ["briefcase>=0.3.22"]
build-backend = "briefcase.build_system"

# ---- project‑wide metadata ----
[tool.briefcase]
project_name  = "Transcribrr"
bundle        = "com.transcribrr"
version       = "0.9.0"

author        = "Your Name"           # ← required
author_email  = "you@example.com"     # ← required
license       = "GPL-3.0-only"                 

requires      = [
    "PyQt6",
    "PyQt6-Qt6",
    "appdirs",
    "colorlog",
    "certifi",
]


# ---- the single desktop application ----
[tool.briefcase.app.transcribrr]
formal_name  = "Transcribrr"
description  = "Speech‑to‑text transcription tool"
sources      = ["app", "main.py"]   # paths that contain your code
icon         = "icons/app/app_icon.icns"

# ---- macOS‑specific options ----
[tool.briefcase.app.transcribrr.macOS]
requires   = []                    # extra wheels if you ever need them
resources  = [
    "icons",                       # complete icon tree
    "config.json",
    "preset_prompts.json",
]
