# ---- mandatory PEP 518 section ----
[build-system]
requires      = ["briefcase>=0.3.22"]
build-backend = "briefcase.build_system"

[tool.briefcase]
project_name   = "Transcribrr"
bundle         = "com.transcribrr"
version        = "1.0.0"
author         = "John Miller"
author_email   = "john@johnbmiller.com"
license.file   = "LICENSE"                   

requires      = [
    "PyQt6",
    "PyQt6-Qt6",
    "appdirs",
    "colorlog",
    "certifi",
]


[tool.briefcase.app.transcribrr]
formal_name  = "Transcribrr"
module_name  = "app"
description  = "Speech‑to‑text transcription tool"
sources      = ["app", "main.py"]   # paths that contain your code
icon         = "icons/app/app_icon.icns"

# ---- macOS‑specific options ----
[tool.briefcase.app.transcribrr.macOS]
requires   = []                    # extra wheels if you ever need them
resources  = [
    "icons",                       # complete icon tree
    "config.json",
    "preset_prompts.json",
]
