# ---- mandatory PEP 518 section ----
[build-system]
requires      = ["briefcase>=0.3.22"]
build-backend = "briefcase.build_system"

[tool.briefcase]
project_name   = "Transcribrr"
bundle         = "com.transcribrr"
version        = "1.0.0"
author         = "John Miller"
author_email   = "john@johnbmiller.com"
license = "GPL-3.0-or-later"                

requires      = ["-r requirements.txt"]


[tool.briefcase.app.transcribrr]
formal_name  = "Transcribrr"
module_name  = "app"
description  = "Speech‑to‑text transcription tool"
sources      = ["app", "main.py"]   # paths that contain your code
icon         = "icons/app/app_icon.icns"

# ---- macOS‑specific options ----
[tool.briefcase.app.transcribrr.macOS]
requires   = ["-r requirements.txt"]
resources  = [
    "icons",                       # complete icon tree
    "config.json",
    "preset_prompts.json",
]
