name: Build Transcribrr – macOS

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'          # run for version tags

env:
  PYTHON_VERSION: '3.9'   # must match the wheel you ship

jobs:
  macos:
    runs-on: macos-14      # Apple‑silicon, builds arm64 fast
    steps:
      # ───────────────────────────────────────────────
      - name: Checkout
        uses: actions/checkout@v4

      # Python 3.9 universal2 (arm64+x86_64)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # System packages required by PyQt6 & your code
      - name: Install Homebrew packages
        run: |
          brew update
          brew install portaudio ffmpeg

      # Python dependencies (PyQt6, Torch, etc.)
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "pyinstaller==6.*" pyqt6 \
                 torch torchvision torchaudio \
                 -r requirements.txt

      # Freeze using the shared transcribrr.spec
      - name: PyInstaller freeze (universal2)
        run: |
          pyinstaller transcribrr.spec --noconfirm --clean \
                                       --target-arch universal2

      # Package the .app bundle
      - name: Zip .app bundle
        run: |
          cd dist
          zip -r Transcribrr-macOS.zip Transcribrr.app

      # Upload artefact for manual download or later release step
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: Transcribrr_macOS
          path: dist/Transcribrr-macOS.zip