name: Build Transcribrr executables

# -------------------------------------------------------------------
# This workflow builds standalone application bundles for:
#   • macOS (.app bundle)
#   • Windows – two flavours
#       – CPU‑only (default PyTorch build)
#       – CUDA 11.8 build (uses --cuda switch in script)
#
# The repo already provides platform‑specific build scripts:
#   • build_github_macos.sh
#   • build_windows_app.bat
#
# The workflow simply invokes those scripts on the appropriate
# GitHub Actions runners and uploads the resulting artefacts so they can
# be downloaded from the “Actions” tab or attached to a release later.
# -------------------------------------------------------------------

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write   # required for release‑uploads on tag pushes

env:
  PYTHON_VERSION: '3.9'

jobs:

  # ────────────────────────────────────────────────────────────
  # macOS bundle – universal app built via build_macos_app.sh
  # ────────────────────────────────────────────────────────────
  macos:
    name: macOS Build
    runs-on: macos-14  # Apple‑silicon runner, faster & supports arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install system dependencies
        run: |
          brew update
          brew install portaudio ffmpeg

      - name: Ensure GitHub Actions build script is executable
        run: chmod +x build_github_macos.sh

      - name: Build Transcribrr macOS
        run: ./build_github_macos.sh

      - name: Compress .app bundle
        run: |
          cd dist
          zip -r Transcribrr-macOS.zip Transcribrr.app

      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: Transcribrr_macOS
          path: dist/Transcribrr-macOS.zip

  # ────────────────────────────────────────────────────────────
  # Windows builds – matrix over [cpu, cuda]
  # ────────────────────────────────────────────────────────────
  windows:
    name: Windows Build (${{ matrix.flavour }})
    runs-on: windows-latest
    strategy:
      matrix:
        flavour: [cpu, cuda]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build (flavour=${{ matrix.flavour }})
        shell: cmd
        run: |
          :: Forward slashes to keep batch happy
          IF "${{ matrix.flavour }}" == "cuda" (
            .\build_windows_app.bat --cuda
          ) ELSE (
            .\build_windows_app.bat
          )

      - name: Install Inno Setup
        shell: pwsh
        run: |
          # Download Inno Setup installer
          $innoSetupUrl = "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe"
          $innoSetupInstaller = "$env:TEMP\innosetup-installer.exe"
          
          Write-Host "Downloading Inno Setup..."
          Invoke-WebRequest -Uri $innoSetupUrl -OutFile $innoSetupInstaller
          
          # Install Inno Setup silently
          Write-Host "Installing Inno Setup..."
          Start-Process -FilePath $innoSetupInstaller -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait
          
          # Add Inno Setup to PATH
          $innoSetupPath = "C:\Program Files (x86)\Inno Setup 6"
          Write-Host "Adding Inno Setup to PATH: $innoSetupPath"
          $env:PATH = "$env:PATH;$innoSetupPath"
          [Environment]::SetEnvironmentVariable("PATH", $env:PATH, "Machine")

      - name: Create Windows Installer
        shell: pwsh
        run: |
          $flavor = "${{ matrix.flavour }}"
          $outputPath = "dist\Transcribrr_$flavor"
          
          if (-Not (Test-Path $outputPath)) {
            Write-Host "Error: Expected output directory $outputPath does not exist!"
            Write-Host "Will try with uppercase directory name as fallback"
            $outputPath = "dist\Transcribrr_" + $flavor.ToUpper()
            
            if (-Not (Test-Path $outputPath)) {
              Write-Host "Error: Uppercase directory $outputPath also doesn't exist!"
              exit 1
            }
          }
          
          # Ensure installer directory exists
          if (-Not (Test-Path "installer")) {
            Write-Host "Creating installer directory"
            New-Item -ItemType Directory -Path "installer"
          }
          
          Write-Host "Creating Windows installer for $flavor build..."
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /DFlavour=$flavor "installer\transcribrr_setup.iss"
          
          # Check if installer was created successfully
          if (Test-Path "dist\Transcribrr-windows-$flavor-setup.exe") {
            Write-Host "Installer created successfully."
          } else {
            Write-Host "Error: Installer creation failed."
            exit 1
          }
          
          # Also create zip archive for backward compatibility or those who prefer portable versions
          Write-Host "Creating zip archive of application directory..."
          Compress-Archive -Path $outputPath -DestinationPath "dist\Transcribrr-windows-$flavor.zip" -Force

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Transcribrr_windows_${{ matrix.flavour }}_installer
          path: dist/Transcribrr-windows-${{ matrix.flavour }}-setup.exe
          
      - name: Upload portable app artifact
        uses: actions/upload-artifact@v4
        with:
          name: Transcribrr_windows_${{ matrix.flavour }}_portable
          path: dist/Transcribrr-windows-${{ matrix.flavour }}.zip

  # ────────────────────────────────────────────────────────────
  # Attach artefacts to GitHub Release when the workflow was
  # triggered by a version tag push (vX.Y.Z).
  # ────────────────────────────────────────────────────────────
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [macos, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            Transcribrr_macOS/Transcribrr-macOS.zip
            Transcribrr_windows_cpu_installer/Transcribrr-windows-cpu-setup.exe
            Transcribrr_windows_cuda_installer/Transcribrr-windows-cuda-setup.exe
            Transcribrr_windows_cpu_portable/Transcribrr-windows-cpu.zip
            Transcribrr_windows_cuda_portable/Transcribrr-windows-cuda.zip
