# .github/workflows/macos.yml   ← complete, validated

name: macOS Briefcase build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:                     # top‑level env is simplest
  PYTHON_VERSION: "3.9"

jobs:
  macos:
    runs-on: macos-14    # Apple‑silicon runner

    steps:
      - uses: actions/checkout@v4

      # ---------- CORRECTLY INDENTED STEP ----------
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # ---------------------------------------------
      
      - name: Locate pip cache dir
        id: pip-cache
        run: echo "dir=$(python -m pip cache dir)" >> "$GITHUB_OUTPUT"

      - name: Cache pip wheels
        uses: actions/cache@v3
        with:
          # resolved path, e.g. /Users/runner/Library/Caches/pip
          path: ${{ steps.pip-cache.outputs.dir }}
          # include Python version + hash of requirement sources
          key: macos-pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements.txt', 'pyproject.toml') }}
          restore-keys: |
            macos-pip-${{ env.PYTHON_VERSION }}-

      - name: Debug cache content
        run: du -sh ${{ steps.pip-cache.outputs.dir }} || true

      - name: Install system libraries
        run: |
          brew update
          brew install portaudio   # ← provides portaudio.h and libportaudio.dylib
          brew install ffmpeg
      - name: Install Briefcase + deps
        run: |
          python -m pip install --upgrade pip briefcase
          python -m pip install -r requirements.txt

      - name: Build .app
        run: briefcase build macOS --no-input --log

      - name: Package (ad‑hoc signed)
        run: briefcase package macOS --adhoc-sign --no-input --log

      - uses: actions/upload-artifact@v4
        with:
          name: Transcribrr_macOS_arm64
          path: dist/macOS/arm64/Transcribrr-*.dmg
