# .github/workflows/macos.yml   ← complete, validated

name: macOS Briefcase build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:                     # top‑level env is simplest
  PYTHON_VERSION: "3.9"

jobs:
  macos:
    runs-on: macos-14    # Apple‑silicon runner

    steps:
      - uses: actions/checkout@v4

      # ---------- CORRECTLY INDENTED STEP ----------
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # ---------------------------------------------
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-
            ${{ runner.os }}-pip-

      - name: Install system libraries
        run: |
          brew update
          brew install portaudio   # ← provides portaudio.h and libportaudio.dylib
          brew install ffmpeg
      - name: Install Briefcase + deps
        run: |
          python -m pip install --upgrade pip briefcase
          python -m pip install -r requirements.txt

      - name: Build .app
        run: briefcase build macOS --no-input --log

      - name: Package (ad‑hoc signed)
        run: briefcase package macOS --adhoc-sign --no-input --log

      - uses: actions/upload-artifact@v4
        with:
          name: Transcribrr_macOS_arm64
          path: dist/macOS/arm64/Transcribrr-*.dmg
